apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa
  template:
    metadata:
      labels:
        app: hpa
    spec:
      containers:
        - name: hello
          image: "k8s.gcr.io/hpa-example"
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 0.5
